### ISSUE TITLE
demo错误解决问题

### ISSUE THREAD

**Issue by yzw1** [myemperor/threejsWithWechatGame#1]
在 game.js文件引入
import './js/libs/weapp-adapter'
import './js/libs/symbol'
这两个文件在官方demo有
在weapp-adapter.js里，搜索createElement，在同样的位置加上以下方法：
createElementNS: function createElementNS(nameSpace, tagName) {
      return this.createElement(tagName)
    },
会报document.createElementNS not a function

**Comment by myemperor** [comment]
不好意思哈，这个问题和我的这个例子有什么关联吗？

**Comment by pengMaster** [comment]
就是你这个例子报错   WAGame.js:4 gameThirdScriptError
document.createElementNS is not a function
TypeError: document.createElementNS is not a function
    at ImageLoader.load (http://127.0.0.1:38460/game/three/three.js:31185:25)
    at TextureLoader.load (http://127.0.0.1:38460/game/three/three.js:31336:11)
    at game3d.start (http://127.0.0.1:38460/game/3dgame.js:41:53)
    at new game3d (http://127.0.0.1:38460/game/3dgame.js:31:14)
    at http://127.0.0.1:38460/game/game.js:11:1
    at require (http://127.0.0.1:38460/game/__dev__/WAGame.js:3:14317)
    at http://127.0.0.1:38460/game/gamePage.html:122:5

**Comment by xchao0213** [comment]
现在还会报另一个错了：
gameThirdScriptError
Cannot assign to read only property 'canvas' of object '#<Window>'
TypeError: Cannot assign to read only property 'canvas' of object '#<Window>'
    at http://127.0.0.1:51202/game/game.js:13:15
    at require (http://127.0.0.1:51202/game/__dev__/WAGame.js:3:13718)
    at http://127.0.0.1:51202/game/gamePage.html:143:5
console.error @ VM555:1
errorReport @ WAGame.js:3
thirdErrorReport @ WAGame.js:3
(anonymous) @ WAGame.js:3
(anonymous) @ WAGame.js:9
(anonymous) @ WAGame.js:4
e @ gamePage.html:1
window.onerror @ VM555:1

**Comment by G96968586** [comment]
你的这个例子一运行蛮多错误的

**Comment by gonnavis** [comment]
已根据楼主方法修改成功, 并提交了pr https://github.com/myemperor/threejsWithWechatGame/pull/2
